[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "torrent-crawler"
version = "2.0.0"
description = "A lightweight and high-performance TUI for searching movie torrents and subtitles."
readme = "README.md"
authors = [
    { name = "fastfingertips" },
    { name = "Rajat Srivastava", email = "rajatsri94@gmail.com" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "textual>=8.0.0",
    "curl_cffi>=0.14.0",
    "beautifulsoup4>=4.14.3",
    "html5lib>=1.1",
    "typer>=0.24.1",
    "loguru>=0.7.3",
    "beaupy>=3.11.0",
    "rich>=14.3.3",
    "Flask>=3.1.3",
    "dynaconf>=3.2.12"
]

[project.scripts]
torrent-crawler = "torrent_crawler.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["torrent_crawler*"]

[tool.ruff]
line-length = 120
target-version = "py39"

[tool.ruff.lint]
# E: Error, F: Pyflakes, I: Isort, B: Bugbear, S: Security (Bandit), UP: Pyupgrade
select = ["E", "F", "I", "B", "S", "UP"]
ignore = ["S113", "S110", "B904", "S104", "E501", "S603", "S606", "S607"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
